### PR TITLE
Added syntax highlight for cat output

### LINKED ISSUE #13: Use Pygments to add syntax highlighting the code when using `cat`
Use [`pygments`](https://pygments.org) to add syntax highlighting. `TerminalFormatter` should work fine to print the output.

### PR DESCRIPTION
**Pull request by mahanthathreyee**
Syntax highlight done for #13

### CODE REVIEW

**Comment by vishal-ramesh2** [comment]
Can you add a couple of screenshots?

**Comment by vishal-ramesh2** [comment]
Also, some terminal require 256 color formatting to be enabled manually for it to work. Can you see if there is some way to check if it is enabled? If it is not, ghub must fall back to Null or 16 color formatting.

**Comment by BBloggsbott** [comment]
Also, the build is failing because of precommit. 
Install pre-commit using
```
pip install pre-commit
```
 and then in the local repository of ghub, run 
```
pre-commit install
```
Then do `pre-commit run` and push the changes made. This should take care of some of the formatting in the files.

**Comment by BBloggsbott** [comment]
There are a few failing tests. I'll fix them.

**Comment by mahanthathreyee** [comment]
> Can you add a couple of screenshots?

Screenshot 2020-03-07 at 2 10 36 PM
Screenshot 2020-03-07 at 2 12 51 PM

**Pull request merged**
